[connections.my_example_connection]
account = "BHQZYSA-ZAB45270"
user = "JRCHARLIE"
authenticator = "externalbrowser"
role = "ACCOUNTADMIN"
warehouse = "<none selected>"
database = "<none selected>"
schema = "<none selected>"